---
# PLAY PARA CONFIGURACAO A INSTANCIA GCP
- hosts: all
  name: Configurando instancia GCP
  remote_user: jean.aps12
  become: yes
  tasks:
    - name: Ajustando Timezone
      timezone:
        name: America/Sao_Paulo
